name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Test in autograding env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
  manual-run:
    name: Test in step env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake . && make all
