name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

env:
  CI: true

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
  manual-run:
    name: Run comp tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake . && make all
